### ISSUE TITLE
[request] add a -version flag

### ISSUE THREAD

**Issue by scalp42** [shoenig/marathonctl#28]
Hi @shoenig,

Thanks a lot for the tool.

This is more of request, but any chance you could add some kind of `-version` flag ? Even if it's the SHA of the commit that'd be fine.

Let me know what you think!

**Comment by shoenig** [comment]
now if you run `go generate` then `go build` it will embed the git hash, and running with -v will return it

```
$ git rev-parse HEAD
3e2e8f6be7b8c2fe391caebbc84c2e90e55bb2b7
$ go generate
$ go build
$ ./marathonctl -v
3e2e8f6be7b8c2fe391caebbc84c2e90e55bb2b7
```
